# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hoangthienan95.github.io/nbdev_tutorial/"

git_url = "https://github.com/hoangthienan95/nbdev_tutorial/tree/{branch}/"

def custom_doc_links(name): return None
